### ISSUE TITLE
Document Installation Procedure - R Studio & R

### ISSUE THREAD

**Issue by graceooh** [uclahs-cds/lintr#23]
Hi! I was wondering if this current version of lintr is following our lab standards because I get suggestions that goes against it. Is there a way to install a version that abides by the standards? Thank you so much!

**Comment by madisonjordan** [comment]
No, I am working on this right now. At the moment, I am working on just getting a version that will at least prevents the false positives you're encountering. See #14. 
The rest of the stuff that actually tells you informative stuff that is incorrect stuff is pending in all the other issues.

I can quickly create the config sometime today or tomorrow that will not give you the false positives. Or tell you how to install it from that branch once I do that. it mostly involves me changing one file called `.lintr`. I will look at how that works for the text editors like VScode and let you know. I'll make sure to add it to the wiki here too. 

If you see the above issue, that means the lab stuff that isn't covered and will need to be checked manually still are:
- enforce single quotes
- [Ratliff indent](https://en.wikipedia.org/wiki/Indentation_style#Ratliff_style) for functions 
- add terminating semicolons
- use dotted.Mixed.case variable names. 
- "yoda test" - I'm not sure anyone uses or enforces this but it's in the manual

All the other lints should be correct. Until I test it today and find out there is one that I missed. I'll update this list if/when that happens.

**Comment by madisonjordan** [comment]
try, from R:
```
devtools::install_github('https://github.com/uclahs-cds/lintr/tree/mbjordan-linter-quotes')
```
then create a `.lintr` file in your home  `~` to use it in with this. 
you can cd into home using `cd ~`

```
linters: linters_with_defaults(
    line_length_linter(120),
    implicit_integer_linter(),
    backport_linter("oldrel-4", except = "R_user_dir")
    brace_linter = NULL,
    object_name_linter = NULL,
    semicolon_linter = NULL,
    single_quotes_linter = NULL,
    double_quotes_linter()
)
```

That should work, but I'll test today.

**Comment by madisonjordan** [comment]
**Current version in review (includes single quotes linting)**

unfortunately I couldn't get the package to install correctly using `devtools::install_github` for my development branch, so you have to clone my branch and use that as a local install.

1. clone repo obviously 
```
git clone git@github.com:uclahs-cds/lintr.git
```
2. cd into the folder and checkout my development branch
```
cd lintr 
git checkout mbjordan-linter-quotes
```

3. install linter from local directory. `Rscript -e` just lets you run a command without entering `R` you can run the command devtools::install from within R if you wish.
```
 Rscript -e 'devtools::install("/PATH/TO/CLONED/BRANCH/mbjordan-linter-quotes")'
```

4. setup `.lintr` config 
```
linters: linters_with_defaults(
    line_length_linter(120),
    backport_linter("oldrel-4", except = "R_user_dir"),
    brace_linter = NULL,
    object_name_linter = NULL,
    semicolon_linter = NULL,
    single_quotes_linter = NULL,
    double_quotes_linter())
```

Let me know if it works.

**Comment by madisonjordan** [comment]
If you hit some linting errors about variable name length or line length please notify me. I can create an issue about it so it can be discussed if we want to have a limit for those. Until then you can disable those too in the same `.lintr` config file using:
```
... previous lints
object_length_linter = NULL,
line_length_linter = NULL)
```

**Comment by graceooh** [comment]
@madisonjordan Hey Madison! Thank you so much for the help. I get an error that says :

devtools::install("/hot/user/jieunoh/lintr/")
Error in eapply(pkgload::ns_env(pkg$package), force, all.names = TRUE) : 
  cannot open file '/usr/local/lib/R/site-library/lintr/R/lintr.rdb': No such file or directory
In addition: Warning message:
In eapply(pkgload::ns_env(pkg$package), force, all.names = TRUE) :
  restarting interrupted promise evaluation

Do you know what the problem may be? Thank you!

**Comment by madisonjordan** [comment]
It seems like you might need to update your `devtools` package or install it, if it isn't. 

in R:
`install.packages("devtools")`

If that doesn't work let me know. It worked when tried the same command on the cluster using your command:
```
devtools::install("/hot/user/jieunoh/lintr/")
```
The only difference I would expect is that my r_env has the dependencies installed. It should only be that one, but here is my environment yaml file listing the packages I have installed, just in case. I followed the instructions on confluence to install using mamba/conda.

```
name: r_env
channels:
  - defaults
dependencies:
  - r-essentials
  - r-base
  - r-devtools
  - ca-certificates
  - openssl
  - r-argparse
```

**Comment by graceooh** [comment]
@madisonjordan it works now but I don't think the BL standards are being implemented even with the ~/.lintr file . Sorry for causing you so much hassle!

**Comment by madisonjordan** [comment]
I can help you on Monday when I'm in office or over Zoom. Your input and feedback is very useful for how to document a usage guide and double checking any issues or finding new ones that I'd need to fix by gathering more real test cases. I'm not sure why it's working on mine so maybe I can get more information from you when you have a chance.

**Comment by graceooh** [comment]
@madisonjordan Yes that would be very helpful. Really appreciate the help! ☺️

**Comment by madisonjordan** [comment]
when using R Studio add `.lintr` file to parent directory such as `/hot/user/<username>` instead of `home` (`/mnt/.../<username>`)

**Comment by jarbet** [comment]
@madisonjordan : I'm curious, does the latest branch of our lintr work for real-time linting in VSCode?

In particular, do my VSCode instructions comment [here](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/lintr+-+R+Linter) work for you?

It works for me using our lintr version 2.0.1.9000
![image](https://user-images.githubusercontent.com/103967480/208182371-6cd7085b-0a6a-4aca-bed8-b799da5d067a.png)

**Comment by madisonjordan** [comment]
> @madisonjordan : I'm curious, does the latest branch of our lintr work for real-time linting in VSCode?
> 
> In particular, do my VSCode instructions comment [here](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/lintr+-+R+Linter) work for you?
> 
> It works for me using our lintr version 2.0.1.9000. As I code, linting problems will automatically display in the 'PROBLEMS' tab in VSCode: ![image](https://user-images.githubusercontent.com/103967480/208182371-6cd7085b-0a6a-4aca-bed8-b799da5d067a.png)

That's a good question. I don't think I have attempted that yet. When you installed lintr and it was working for this in vscode, was it back before I updated master to version 3? 
If you didn't do anything special I would imagine that it would work once I merge the changes the same as version 2. I'm not sure if switching branches as I described above would work with the vscode R language server. But the .lintr config itself I specified should work if we are able to install our fork. 

I will look into it. Eventually we should be creating issues / PRs to r-lib directly for our linters to be added and maintained by them. So at that point it would work for sure with the typical custom config.

**Comment by madisonjordan** [comment]
@jarbet 

**Mamba/conda install:**
(radian is optional)
```
conda activate r_env
mamba install radian
mamba install r-languageserver
```


**Install lintr:**
This installs a specific branch if not merged. Otherwise omit `@<branch/tag>`.
```
Rscript -e 'remotes::install_github("uclahs-cds/lintr@mbjordan-linter-quotes")'
```

**`settings.json` for VS Code on Mac:**
replace with your username obviously. use normal R path for `r.rterm.mac` if you didn't install radian.
```
    "r.rpath.mac": "/Users/<username>/miniconda3/envs/r_env/bin/R",
    "r.rterm.mac": "/Users/<username>/miniconda3/envs/r_env/bin/radian",
    "r.bracketedPaste": true,
    "r.plot.useHttpgd": true,
    "r.alwaysUseActiveTerminal": true,
    "r.rterm.option": [
            "--no-save",
            "--no-restore",
            "--r-binary=/Users/<username>/miniconda3/envs/r_env/bin/R"
    ],
    "editor.bracketPairColorization.enabled": true,
    "editor.guides.bracketPairs": "active",
    "editor.detectIndentation": false,
    "editor.renderWhitespace": "all",
    "indentRainbow.lightIndicatorStyleLineWidth": 4
```

---

formal instructions to follow for all comments above to be created on wiki and linked to confluence.
The linux instructions will be done later when I test those.

**Comment by madisonjordan** [comment]
Installations for R Studio and VS Code now added to [wiki](https://github.com/uclahs-cds/lintr/wiki).
